config/routes.rb
Rails.application.routes.draw do
  resources :dogs
  root to: "dogs#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: %i[ show edit update destroy ]

  def index
    @dogs = Dog.all
  end

  def show
    # @dog = Dog.find(params[:id])
  end

  def new
    @dog = Dog.new
  end

  def edit
    # @dog = Dog.find(params[:id])
  end

  def create
    @dog = Dog.new(dog_params)

    if @dog.save
      redirect_to root_path, notice: "Recipe was succesfully created."
    else
      render :new
    end
  end

  def update
    # dog = Dog.find(dog_params[:id])
    if @dog.update(dog_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy

    redirect_to root_path
  end

  private
    def set_dog
      @dog = Dog.find(params[:id])
    end

    def dog_params
      params.require(:dog).permit(:name, :breed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/delete.html.erb
<h1>Dogs#delete</h1>
<p>Find me in app/views/dogs/delete.html.erb</p>

app/views/dogs/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 mb-4 display-4">Edit dog</h4>
  </div>
  
  <div class="row justify-content-center">
    <%= form_with(model: @dog, local: true) do |form| %>
      <div class="form-group">
        <%= form.label :name%>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :breed %>
        <%= form.text_area :breed, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.submit class: 'form-control btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/dogs/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 display-4">List of Dogs</h4>
  </div>
  <%= link_to 'Add New Dog', new_dog_path %>

   <% if @dogs.present? %>
    <div class="row justify-content-center">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col">
              Name
            </th>

            <th scope="col">
              Breed
            </th>

            <th scope="col" colspan="3">
              Action
            </th>
          </tr>
        </thead>
        
        <tbody>
          <% @dogs.each do |dog| %>
            <tr>
              <td>
                <%= dog.name %>
              </td>

              <td>
                <%= dog.breed %>
              </td>
              
              <td>
                <%= link_to "Show Dog", dog_path(dog.id) %>
              </td>

              <td> 
                <%= link_to "Edit", edit_dog_path(dog.id) %>
              </td>

              <td>
                <%= button_to "Destroy", dog_path(dog.id), method: :delete, data: { confirm: "Are you sure you want to delete this dog?" } %>
              </td>              
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>
</div>

app/views/dogs/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 mb-4 display-4">New Dog</h4>
  </div>

  <div class="row justify-content-center">
    <%= form_with scope: :dog, url: dogs_path, local: true do |form| %>
      <div class="form-group">
        <%= form.label :name%>

        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :breed %>

        <%= form.text_area :breed, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.submit class: 'form-control btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/dogs/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 mb-4 display-4">Dog # <%= @dog.id %></h4>
  </div>
  
  <div class="row justify-content-center">
    <table class="table">
      <tbody>
        <tr>
          <th>Name:</th>
          
          <td><%= @dog.name %></td>
        </tr>
        
        <tr>
          <th>Breed:</th>
          
          <td><%= @dog.breed %></td>
        </tr>
      </tbody>
    </table>
  </div>
  
  <%= link_to "Back to Index", root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudBootstrap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet"   href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>